/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package estudiantesupc;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author keiinerp
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    ArrayList<Estudiante> listaEstudiante;
    ArrayList<Estudiante> listaEstudiantesAptos;
    ArrayList<Estudiante> estudiantesNoBeneficiados;

    public Principal() {
        initComponents();
        listaEstudiante = Archivos.leerEnTexto();
        listaEstudiantesAptos = Archivos.leerBinario();
        estudiantesNoBeneficiados = Archivos.leerBinarioNo();
        pintarTabla();
        asignarMatriculaYValidar();
    }

    private void pintarTabla() {
        DefaultTableModel modelo = new DefaultTableModel();
        String[] columnas = {"CODIGO", "NOMBRE", "SISBEN", "PROMEDIO", "EDAD", "BENEFICIADO"};
        modelo.setColumnIdentifiers(columnas);
        for (Estudiante p : listaEstudiante) {
            String[] fila = {String.valueOf(p.getCodigo()), p.getNombre(), String.valueOf(p.getSisben()), String.valueOf(p.getPromedio()), String.valueOf(p.getEdad())};
            modelo.addRow(fila);
        }
        estudiantesTabla.setModel(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        estudiantesTabla = new javax.swing.JTable();
        identificacionABuscar = new javax.swing.JTextField();
        encontrarBoton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        datosEstudianteTexto = new javax.swing.JTextPane();
        matriculaText = new javax.swing.JTextField();
        asignarMatriculaBoton = new javax.swing.JButton();
        procesarBoton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        estudiantesTabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                estudiantesTablaMouseClicked(evt);
            }
        });
        estudiantesTabla.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                estudiantesTablaKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(estudiantesTabla);

        encontrarBoton.setText("Encontrar");
        encontrarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                encontrarBotonActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(datosEstudianteTexto);

        asignarMatriculaBoton.setText("Asignar Matrícula");
        asignarMatriculaBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                asignarMatriculaBotonActionPerformed(evt);
            }
        });

        procesarBoton.setText("Procesar");
        procesarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                procesarBotonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(identificacionABuscar)
                    .addComponent(jScrollPane2)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(matriculaText, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(procesarBoton)
                            .addComponent(asignarMatriculaBoton))))
                .addGap(18, 18, 18)
                .addComponent(encontrarBoton)
                .addGap(32, 32, 32))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(identificacionABuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(encontrarBoton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(matriculaText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(asignarMatriculaBoton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                        .addComponent(procesarBoton))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void encontrarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_encontrarBotonActionPerformed
        if (encontrar() == 1) {
            datosEstudianteTexto.setText("NOMBRE:   " + estudianteEncontrado.getNombre() + "    CODIGO: " + estudianteEncontrado.getCodigo() + "\n"
                    + "SISBEN:  " + estudianteEncontrado.getSisben() + "  PROMEDIO:   " + estudianteEncontrado.getPromedio());
        }
    }//GEN-LAST:event_encontrarBotonActionPerformed

    private void estudiantesTablaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_estudiantesTablaKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_estudiantesTablaKeyTyped

    private void estudiantesTablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_estudiantesTablaMouseClicked
        int posicionSeleccionada = estudiantesTabla.getSelectedRow();
        if (evt.getClickCount() == 1) {
            for (Estudiante estudianteEncontrado1 : listaEstudiante) {
                estudianteEncontrado1 = listaEstudiante.get(posicionSeleccionada);
                datosEstudianteTexto.setText("NOMBRE:   " + estudianteEncontrado1.getNombre() + "    CODIGO: " + estudianteEncontrado1.getCodigo() + "\n"
                        + "SISBEN:  " + estudianteEncontrado1.getSisben() + "  PROMEDIO:   " + estudianteEncontrado1.getPromedio());
                identificacionABuscar.setText(estudianteEncontrado1.getCodigo());
            }
        }
    }//GEN-LAST:event_estudiantesTablaMouseClicked

    private void asignarMatriculaBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_asignarMatriculaBotonActionPerformed
        valorMatricula = Double.valueOf(matriculaText.getText());
    }//GEN-LAST:event_asignarMatriculaBotonActionPerformed

    private void procesarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_procesarBotonActionPerformed
        EstudiantesBeneficiados estudiantesBeneficiadosVentana = new EstudiantesBeneficiados(this, true);
        estudiantesBeneficiadosVentana.setVisible(true);
    }//GEN-LAST:event_procesarBotonActionPerformed
    public int posicionEstudiante = -1;
    public static double valorMatricula = 900000;

    private void asignarMatriculaYValidar() {        
        int beneficiario = 0;        
        if (posicionEstudiante != -1) {
            for (Estudiante estudiante : listaEstudiante) {
                if (estudiante.getPromedio() >= 4) {
                    estudiante.setBeneficiado("BENEFICIARIO");
                    estudiante.setMatricula(valorMatricula - (valorMatricula * 0.7));
                    listaEstudiante.add(estudiante);
                    listaEstudiantesAptos.add(estudiante);
                    beneficiario = 1;
                    Archivos.escribirBinario(listaEstudiantesAptos);
                    break;
                } else if (estudiante.getPromedio() >= 3.5 && 30 > estudiante.getSisben()) {
                    estudiante.setMatricula(valorMatricula - (valorMatricula * 0.6));
                    estudiante.setBeneficiado("BENEFICIARIO");
                    listaEstudiante.add(estudiante);
                    listaEstudiantesAptos.add(estudiante);
                    beneficiario = 1;
                    Archivos.escribirBinario(listaEstudiantesAptos);
                    break;
                } else if (estudiante.getPromedio() >= 3.2 && 20 > estudiante.getSisben()) {
                    estudiante.setMatricula(valorMatricula - (valorMatricula * 0.4));
                    estudiante.setBeneficiado("BENEFICIARIO");
                    listaEstudiante.add(estudiante);
                    listaEstudiantesAptos.add(estudiante);
                    beneficiario = 1;
                    Archivos.escribirBinario(listaEstudiantesAptos);
                    break;
                } else if (estudiante.getPromedio() >= 3.0 && 18 > estudiante.getEdad()) {
                    estudiante.setMatricula(valorMatricula - (valorMatricula * 0.2));
                    estudiante.setBeneficiado("BENEFICIARIO");
                    listaEstudiante.add(estudiante);
                    listaEstudiantesAptos.add(estudiante);
                    beneficiario = 1;
                    Archivos.escribirBinario(listaEstudiantesAptos);
                    break;
                }
                if (20 > estudiante.getEdad()) {
                    estudiante.setMatricula(valorMatricula - (valorMatricula * 0.1));
                    estudiante.setBeneficiado("BENEFICIARIO");
                    listaEstudiantesAptos.add(estudiante);
                    listaEstudiante.add(estudiante);
                    Archivos.escribirBinario(listaEstudiantesAptos);
                    beneficiario = 1;
                    break;
                }
                if (beneficiario == 0) {
                    estudiantesNoBeneficiados.add(estudiante);
                    listaEstudiante.add(estudiante);
                }
            }
        }
    }

    public int encontrar() {
        int encontrado = 0;
        for (Estudiante estudiante : listaEstudiante) {
            if (identificacionABuscar.getText().equals(estudiante.getCodigo())) {
                encontrado = 1;
                estudianteEncontrado = estudiante;
            }
        }
        return encontrado;
    }
    public Estudiante estudianteEncontrado;

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton asignarMatriculaBoton;
    private javax.swing.JTextPane datosEstudianteTexto;
    private javax.swing.JButton encontrarBoton;
    private javax.swing.JTable estudiantesTabla;
    private javax.swing.JTextField identificacionABuscar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField matriculaText;
    private javax.swing.JButton procesarBoton;
    // End of variables declaration//GEN-END:variables
}
